/**
 * Реестр типов уведомлений (F-05-004) — порт `src/areas/notify/lib/registry.ts::TYPE_REGISTRY` фронта, слово в
 * слово (имена/описания/дефолты/шаблоны на ru/hy/en). Решение владельца (28.09, этап 21 «notify+integrations»,
 * попытка 3): сервер строит каталог ПОД экран — 29 настраиваемых + 2 служебных типа, НЕ 88 (то была верхняя
 * граница нумерации Altegio, не количество типов). Статичен: имя/описание/дефолт-шаблон/дефолт-каналы не
 * трогает бизнес — только `NotifyTypeOverride` (schema.prisma) поверх. Меняется только вместе с фронтовым
 * реестром — если тот меняется, обновите оба файла одним изменением, тесты фронта (`liveLog.test.ts`) сверяют
 * фронт сам с собой, эта копия сверяется вручную при правке.
 *
 * НЕ ПУТАТЬ с `kinds.ts`/`NotifyTypesService` — те питают НАСТОЯЩУЮ отправку (13 kind, docs/backend/05 §3,
 * `bookings.service.ts`/`notify-dispatch.service.ts`/`notify-reminders.ts` читают их напрямую). Эта модель — для
 * экрана-каталога `/biz/notifications` (`GET/PUT .../notify/types`), которую видит владелец салона; сервер эти
 * типы САМ не отправляет (тот же статус, что был на моке — экран настраивает, реальная рассылка идёт по kinds.ts).
 */

export type NotifyChannel = 'push' | 'adminApp' | 'email' | 'sms' | 'brandedApp' | 'whatsapp' | 'telegram';
export type NotifyRecipient = 'client' | 'admin' | 'staff' | 'adminStaff';
export type NotifyClientGroup = 'attendance' | 'quality' | 'retention' | 'other';
export type NotifyScenario = 'off' | 'always' | 'fallback';

export interface RegistryLocalizedText {
  ru: string;
  hy?: string;
  en?: string;
}

export interface RegistryTypeConditions {
  timingHours?: number;
  emailTimingHours?: number;
  useSpecificTime?: boolean;
  specificTime?: string;
  rescheduleThresholdMinutes?: number;
  rescheduleSource?: 'client' | 'staff' | 'all';
  inviteAfterHours?: number;
  inviteStatusFilter?: 'cancelled' | 'noShow' | 'all';
  reviewDelayMinutes?: number;
  reviewExcludeServiceIds?: string[];
  reviewExcludeIfReviewed?: { location?: boolean; staff?: boolean; service?: boolean };
  birthdayMode?: 'onDay' | 'daysBefore';
  birthdayDaysBefore?: number;
  birthdayTimeOfDay?: string;
  discountExpiryDaysBefore?: number;
  winbackAfterDays?: number;
  serviceTimingHours?: Record<string, number>;
}

export interface TypeDef {
  code: number;
  recipient: NotifyRecipient;
  group?: NotifyClientGroup;
  nameRu: string;
  nameEn: string;
  nameHy: string;
  descriptionRu: string;
  descriptionEn: string;
  descriptionHy: string;
  enabledDefault: boolean;
  availableChannels: NotifyChannel[];
  defaultScenario: Partial<Record<NotifyChannel, NotifyScenario>>;
  alwaysOn?: boolean;
  systemLocked?: boolean;
  templateRu: string;
  templateEn?: string;
  templateHy?: string;
  conditionsDefault?: RegistryTypeConditions;
}

const CLIENT_DEFAULT: Partial<Record<NotifyChannel, NotifyScenario>> = { push: 'always' };
const CLIENT_REMINDER_DEFAULT: Partial<Record<NotifyChannel, NotifyScenario>> = { push: 'always', telegram: 'always' };
const ADMIN_DEFAULT: Partial<Record<NotifyChannel, NotifyScenario>> = { adminApp: 'always', email: 'always' };

export const TYPE_REGISTRY: TypeDef[] = [
  {
    code: 2,
    recipient: 'client',
    group: 'attendance',
    nameRu: 'Клиент записался онлайн',
    nameEn: 'Client booked online',
    nameHy: 'Հաճախորդը գրանցվել է առցանց',
    descriptionRu: 'Клиент сам записался онлайн — подтверждаем детали визита.',
    descriptionEn: 'Client booked online themselves — we confirm the visit details.',
    descriptionHy: 'Հաճախորդն ինքն է գրանցվել առցանց․ հաստատում ենք այցի մանրամասները։',
    enabledDefault: true,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: вы записаны — {service}, {date} в {time}. Мастер: {staff}. Адрес: {address}. Перенести или отменить: {link}',
    templateEn: '{companyName}: you are booked — {service}, {date} at {time}. Specialist: {staff}. Address: {address}. Reschedule or cancel: {link}',
    templateHy: '{companyName}․ դուք գրանցված եք՝ {service}, {date}, ժամը {time}։ Վարպետ՝ {staff}։ Հասցե՝ {address}։ Տեղափոխել կամ չեղարկել՝ {link}',
  },
  {
    code: 8,
    recipient: 'client',
    group: 'attendance',
    nameRu: 'Администратор записал клиента',
    nameEn: 'Admin booked the client',
    nameHy: 'Ադմինիստրատորը գրանցել է հաճախորդին',
    descriptionRu: 'Администратор записал клиента в журнале — клиент получает подтверждение.',
    descriptionEn: 'An admin created the booking in the journal — the client gets a confirmation.',
    descriptionHy: 'Ադմինիստրատորը գրանցումն արել է մատյանում․ հաճախորդը ստանում է հաստատում։',
    enabledDefault: true,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: вас записали — {service}, {date} в {time}. Мастер: {staff}. Подробности, перенос и отмена: {link}',
    templateEn: '{companyName}: you have been booked — {service}, {date} at {time}. Specialist: {staff}. Details, reschedule or cancel: {link}',
    templateHy: '{companyName}․ ձեզ գրանցել են՝ {service}, {date}, ժամը {time}։ Վարպետ՝ {staff}։ Մանրամասներ, տեղափոխում և չեղարկում՝ {link}',
  },
  {
    code: 9,
    recipient: 'client',
    group: 'attendance',
    nameRu: 'Запись подтверждена',
    nameEn: 'Booking confirmed',
    nameHy: 'Գրանցումը հաստատված է',
    descriptionRu: 'Администратор подтвердил запись — сообщаем клиенту.',
    descriptionEn: 'An admin confirmed the booking — we let the client know.',
    descriptionHy: 'Ադմինիստրատորը հաստատել է գրանցումը․ տեղեկացնում ենք հաճախորդին։',
    enabledDefault: true,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: ваша запись на {date} в {time} подтверждена. Подробности: {link}',
    templateEn: '{companyName}: your booking {date} at {time} is confirmed. Details: {link}',
    templateHy: '{companyName}․ ձեր գրանցումը՝ {date}, ժամը {time}, հաստատված է։ Մանրամասներ՝ {link}',
  },
  {
    code: 74,
    recipient: 'client',
    group: 'attendance',
    nameRu: 'Изменение записи',
    nameEn: 'Booking changed',
    nameHy: 'Գրանցման փոփոխություն',
    descriptionRu: 'Время, мастер или услуга записи изменились.',
    descriptionEn: 'The booking time, staff or service has changed.',
    descriptionHy: 'Փոխվել է գրանցման ժամը, վարպետը կամ ծառայությունը։',
    enabledDefault: true,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: запись изменена. Теперь: {service}, {date} в {time}, мастер: {staff}. Подробности: {link}',
    templateEn: '{companyName}: your booking has changed. Now: {service}, {date} at {time}, specialist: {staff}. Details: {link}',
    templateHy: '{companyName}․ ձեր գրանցումը փոխվել է։ Այժմ՝ {service}, {date}, ժամը {time}, վարպետ՝ {staff}։ Մանրամասներ՝ {link}',
    conditionsDefault: { rescheduleThresholdMinutes: 5, rescheduleSource: 'all' },
  },
  {
    code: 73,
    recipient: 'client',
    group: 'attendance',
    nameRu: 'Просим подтвердить визит',
    nameEn: 'Ask to confirm the visit',
    nameHy: 'Խնդրում ենք հաստատել այցը',
    descriptionRu: 'Просим клиента подтвердить, что придёт на визит.',
    descriptionEn: 'We ask the client to confirm they will come.',
    descriptionHy: 'Խնդրում ենք հաճախորդին հաստատել, որ կգա այցի։',
    enabledDefault: false,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: подтвердите визит {date} в {time} ({service}, мастер: {staff}). Подтвердить или отменить: {link}',
    templateEn: '{companyName}: please confirm your visit {date} at {time} ({service}, specialist: {staff}). Confirm or cancel: {link}',
    templateHy: '{companyName}․ խնդրում ենք հաստատել այցը՝ {date}, ժամը {time} ({service}, վարպետ՝ {staff})։ Հաստատել կամ չեղարկել՝ {link}',
    conditionsDefault: { timingHours: 24, useSpecificTime: false, specificTime: '14:00' },
  },
  {
    code: 1,
    recipient: 'client',
    group: 'attendance',
    nameRu: 'Напоминание о визите',
    nameEn: 'Visit reminder',
    nameHy: 'Այցի հիշեցում',
    descriptionRu: 'Напоминаем о записи заранее, чтобы клиент не забыл.',
    descriptionEn: 'A heads-up before the visit so the client does not forget.',
    descriptionHy: 'Նախապես հիշեցնում ենք գրանցման մասին, որ հաճախորդը չմոռանա։',
    enabledDefault: true,
    // ⭐ 01.10.2026: Telegram-бот — клиенту без приложения, за 24 ч и за 2 ч (telegram-reminders.ts читает этот тип:
    // выключен тип или сценарий Telegram «Не отправлять» — в Telegram ничего не уходит). Как TYPE_REGISTRY фронта.
    availableChannels: ['push', 'telegram', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_REMINDER_DEFAULT,
    templateRu: '{companyName}: напоминаем о визите {date} в {time} — {service}, мастер: {staff}. Адрес: {address}. Если не получается прийти: {link}',
    templateEn: '{companyName}: a reminder of your visit {date} at {time} — {service}, specialist: {staff}. Address: {address}. If you can’t make it: {link}',
    templateHy: '{companyName}․ հիշեցնում ենք այցի մասին՝ {date}, ժամը {time}՝ {service}, վարպետ՝ {staff}։ Հասցե՝ {address}։ Եթե չեք կարող գալ՝ {link}',
    conditionsDefault: { timingHours: 1, emailTimingHours: 12 },
  },
  {
    code: 4,
    recipient: 'client',
    group: 'attendance',
    nameRu: 'Отмена записи',
    nameEn: 'Booking cancelled',
    nameHy: 'Գրանցման չեղարկում',
    descriptionRu: 'Запись отменена — сообщаем клиенту.',
    descriptionEn: 'The booking was cancelled — we let the client know.',
    descriptionHy: 'Գրանցումը չեղարկվել է․ տեղեկացնում ենք հաճախորդին։',
    enabledDefault: true,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: ваша запись на {date} в {time} отменена. Записаться снова: {bookingLink}',
    templateEn: '{companyName}: your booking {date} at {time} was cancelled. Book again: {bookingLink}',
    templateHy: '{companyName}․ ձեր գրանցումը՝ {date}, ժամը {time}, չեղարկվել է։ Կրկին գրանցվել՝ {bookingLink}',
  },
  {
    code: 75,
    recipient: 'client',
    group: 'attendance',
    nameRu: 'Клиент не пришёл',
    nameEn: 'Client did not show up',
    nameHy: 'Հաճախորդը չի եկել',
    descriptionRu: 'Клиент не пришёл — запись закрыта статусом «не пришёл».',
    descriptionEn: 'The client did not show up — the booking was closed as a no-show.',
    descriptionHy: 'Հաճախորդը չի եկել․ գրանցումը փակվել է «չի եկել» կարգավիճակով։',
    enabledDefault: true,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: вы не пришли на запись {date} в {time}. Будем рады видеть в другой раз: {bookingLink}',
    templateEn: '{companyName}: you missed your booking {date} at {time}. We would love to see you another time: {bookingLink}',
    templateHy: '{companyName}․ դուք չեկաք գրանցմանը՝ {date}, ժամը {time}։ Սիրով կսպասենք ձեզ մեկ այլ անգամ՝ {bookingLink}',
  },
  {
    code: 72,
    recipient: 'client',
    group: 'attendance',
    nameRu: 'Зовём вернуться того, кто не дошёл',
    nameEn: 'Invite a no-show back',
    nameHy: 'Կրկին հրավիրում ենք չեկածներին',
    descriptionRu: 'Приглашаем записаться снова тех, кто не дошёл в прошлый раз.',
    descriptionEn: 'We invite clients who no-showed to book again.',
    descriptionHy: 'Կրկին գրանցվելու ենք հրավիրում նրանց, ովքեր նախորդ անգամ չեն եկել։',
    enabledDefault: false,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: заметили, что вы не смогли прийти. Запишитесь на удобное время: {bookingLink}',
    templateEn: '{companyName}: we noticed you could not make it. Book a time that suits you: {bookingLink}',
    templateHy: '{companyName}․ նկատեցինք, որ չկարողացաք գալ։ Գրանցվեք ձեզ հարմար ժամի՝ {bookingLink}',
    conditionsDefault: { inviteAfterHours: 0, inviteStatusFilter: 'all' },
  },
  {
    code: 6,
    recipient: 'client',
    group: 'quality',
    nameRu: 'Спрашиваем впечатление (запись онлайн)',
    nameEn: 'Ask how it went (booked online)',
    nameHy: 'Հարցնում ենք տպավորությունը (առցանց գրանցում)',
    descriptionRu: 'Спрашиваем, понравился ли визит, простым «★», как только клиент отмечен пришедшим.',
    descriptionEn: 'A simple “liked it? ★” question once the visit is marked as attended.',
    descriptionHy: 'Պարզ «★» հարցով հարցնում ենք՝ դուր եկա՞վ այցը, հենց որ հաճախորդը նշվում է որպես եկած։',
    enabledDefault: true,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: спасибо за визит! Понравилось? Оцените ★: {reviewLink}',
    templateEn: '{companyName}: thanks for visiting! Did you like it? Rate it ★: {reviewLink}',
    templateHy: '{companyName}․ շնորհակալություն այցի համար։ Դուր եկա՞վ։ Գնահատեք ★՝ {reviewLink}',
    conditionsDefault: {
      reviewDelayMinutes: 5,
      reviewExcludeServiceIds: [],
      reviewExcludeIfReviewed: { location: true, staff: false, service: false },
    },
  },
  {
    code: 20,
    recipient: 'client',
    group: 'quality',
    nameRu: 'Спрашиваем впечатление (запись из журнала)',
    nameEn: 'Ask how it went (booked in journal)',
    nameHy: 'Հարցնում ենք տպավորությունը (գրանցում մատյանից)',
    descriptionRu: 'То же самое, но для визита, который в журнал внёс администратор.',
    descriptionEn: 'The same, for a visit an admin logged in the journal.',
    descriptionHy: 'Նույնը, բայց այն այցի համար, որը մատյանում գրանցել է ադմինիստրատորը։',
    enabledDefault: true,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: спасибо за визит! Понравилось? Оцените ★: {reviewLink}',
    templateEn: '{companyName}: thanks for visiting! Did you like it? Rate it ★: {reviewLink}',
    templateHy: '{companyName}․ շնորհակալություն այցի համար։ Դուր եկա՞վ։ Գնահատեք ★՝ {reviewLink}',
    conditionsDefault: { reviewDelayMinutes: 5, reviewExcludeServiceIds: [], reviewExcludeIfReviewed: { location: true, staff: false, service: false } },
  },
  {
    code: 3,
    recipient: 'client',
    group: 'retention',
    nameRu: 'Поздравление с днём рождения',
    nameEn: 'Birthday greeting',
    nameHy: 'Ծննդյան օրվա շնորհավորանք',
    descriptionRu: 'Автоматическое поздравление в день рождения клиента.',
    descriptionEn: 'An automatic greeting on the client’s birthday.',
    descriptionHy: 'Ավտոմատ շնորհավորանք հաճախորդի ծննդյան օրը։',
    enabledDefault: true,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: 'С днём рождения, {clientName}! Желаем хорошего настроения и ждём в гости: {bookingLink}. {companyName}',
    templateEn: 'Happy birthday, {clientName}! Wishing you a great day — come see us: {bookingLink}. {companyName}',
    templateHy: '{clientName}, շնորհավորում ենք ձեր ծննդյան օրվա առթիվ։ Սպասում ենք ձեզ՝ {bookingLink}։ {companyName}',
    conditionsDefault: { birthdayMode: 'onDay', birthdayDaysBefore: 3, birthdayTimeOfDay: '10:00' },
  },
  {
    code: 16,
    recipient: 'client',
    group: 'retention',
    nameRu: 'Новая скидка',
    nameEn: 'New discount',
    nameHy: 'Նոր զեղչ',
    descriptionRu: 'Клиенту назначили новую скидку.',
    descriptionEn: 'The client got a new discount.',
    descriptionHy: 'Հաճախորդին նոր զեղչ է տրամադրվել։',
    enabledDefault: false,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: вам назначена скидка {discount}%. Записаться: {bookingLink}',
    templateEn: '{companyName}: you have been given a {discount}% discount. Book: {bookingLink}',
    templateHy: '{companyName}․ ձեզ տրամադրվել է {discount}% զեղչ։ Գրանցվել՝ {bookingLink}',
  },
  {
    code: 17,
    recipient: 'client',
    group: 'retention',
    nameRu: 'Окончание действия скидки',
    nameEn: 'Discount ending',
    nameHy: 'Զեղչի ավարտ',
    descriptionRu: 'Скидка клиента скоро перестанет действовать.',
    descriptionEn: 'The client’s discount is about to expire.',
    descriptionHy: 'Հաճախորդի զեղչը շուտով կդադարի գործել։',
    enabledDefault: false,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: ваша скидка {discount}% закончится через {days} дн. Успейте записаться: {bookingLink}',
    templateEn: '{companyName}: your {discount}% discount ends in {days} day(s). Book in time: {bookingLink}',
    templateHy: '{companyName}․ ձեր {discount}% զեղչը կավարտվի {days} օրից։ Հասցրեք գրանցվել՝ {bookingLink}',
    conditionsDefault: { discountExpiryDaysBefore: 3 },
  },
  {
    code: 55,
    recipient: 'client',
    group: 'retention',
    nameRu: 'Приглашение на повторный визит',
    nameEn: 'Invitation to come back',
    nameHy: 'Հրավեր կրկնակի այցի',
    descriptionRu: 'Клиент давно не был — приглашаем записаться снова.',
    descriptionEn: 'The client has not visited in a while — we invite them back.',
    descriptionHy: 'Հաճախորդը վաղուց չի եղել․ հրավիրում ենք կրկին գրանցվել։',
    enabledDefault: true,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: давно вас не было — пора снова на «{service}». Запишитесь на удобное время: {bookingLink}',
    templateEn: '{companyName}: it has been a while since your “{service}”. Book a convenient time: {bookingLink}',
    templateHy: '{companyName}․ վաղուց չեք եղել՝ «{service}»։ Գրանցվեք ձեզ հարմար ժամի՝ {bookingLink}',
    conditionsDefault: { winbackAfterDays: 14 },
  },
  {
    code: 85,
    recipient: 'client',
    group: 'other',
    nameRu: 'Ссылка на оплату визита',
    nameEn: 'Payment link for the client',
    nameHy: 'Այցի վճարման հղում',
    descriptionRu: 'Ссылка на онлайн-оплату визита (заработает, когда в платформе появится оплата).',
    descriptionEn: 'A link to pay for the visit online (starts working once online payments ship).',
    descriptionHy: 'Այցի առցանց վճարման հղում (կաշխատի, երբ հարթակում հայտնվի վճարումը)։',
    enabledDefault: true,
    availableChannels: ['push', 'email', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: оплатите визит {date} в {time} по ссылке: {paymentLink}',
    templateEn: '{companyName}: pay for your visit {date} at {time} via the link: {paymentLink}',
    templateHy: '{companyName}․ վճարեք այցի համար ({date}, ժամը {time}) հղումով՝ {paymentLink}',
  },
  {
    code: 7,
    recipient: 'client',
    group: 'other',
    nameRu: 'Код входа клиента',
    nameEn: 'Client login code',
    nameHy: 'Հաճախորդի մուտքի կոդ',
    descriptionRu: 'Одноразовый код, которым клиент подтверждает номер при входе: WhatsApp или Telegram, SMS — запасной канал.',
    descriptionEn: 'A one-time code the client uses to confirm their phone: WhatsApp or Telegram, SMS as a fallback.',
    descriptionHy: 'Միանվագ կոդ, որով հաճախորդը մուտք գործելիս հաստատում է համարը՝ WhatsApp կամ Telegram, SMS՝ պահեստային ալիք։',
    enabledDefault: true,
    availableChannels: ['whatsapp', 'telegram', 'sms'],
    defaultScenario: { whatsapp: 'always', telegram: 'always', sms: 'fallback' },
    alwaysOn: true,
    templateRu: 'Код подтверждения: {code}',
    templateEn: 'Confirmation code: {code}',
    templateHy: 'Հաստատման կոդ՝ {code}',
    systemLocked: true,
  },
  {
    code: 65,
    recipient: 'client',
    group: 'other',
    nameRu: 'Оплата прошла',
    nameEn: 'Payment received',
    nameHy: 'Վճարումը կատարված է',
    descriptionRu: 'Оплата визита онлайн прошла успешно (заработает, когда появится оплата).',
    descriptionEn: 'The online payment for the visit went through (starts working once payments ship).',
    descriptionHy: 'Այցի առցանց վճարումը հաջողվել է (կաշխատի, երբ հայտնվի վճարումը)։',
    enabledDefault: false,
    availableChannels: ['push', 'sms', 'brandedApp'],
    defaultScenario: CLIENT_DEFAULT,
    templateRu: '{companyName}: оплата {amount} ֏ прошла. Ждём вас {date} в {time}.',
    templateEn: '{companyName}: payment of {amount} AMD received. See you {date} at {time}.',
    templateHy: '{companyName}․ {amount} ֏ վճարումը ստացված է։ Սպասում ենք ձեզ {date}, ժամը {time}։',
  },
  {
    code: 10,
    recipient: 'admin',
    nameRu: 'Клиент записался онлайн',
    nameEn: 'Client booked online',
    nameHy: 'Հաճախորդը գրանցվել է առցանց',
    descriptionRu: 'Клиент записался онлайн — сообщаем администратору.',
    descriptionEn: 'A client booked online — the admin is notified.',
    descriptionHy: 'Հաճախորդը գրանցվել է առցանց․ տեղեկացնում ենք ադմինիստրատորին։',
    enabledDefault: true,
    availableChannels: ['adminApp', 'email', 'sms'],
    defaultScenario: ADMIN_DEFAULT,
    templateRu: 'Новая онлайн-запись: {clientName}, {service}, {date} {time}, мастер: {staff}.',
    templateEn: 'New online booking: {clientName}, {service}, {date} {time}, specialist: {staff}.',
    templateHy: 'Նոր առցանց գրանցում՝ {clientName}, {service}, {date} {time}, վարպետ՝ {staff}։',
  },
  {
    code: 56,
    recipient: 'admin',
    nameRu: 'Коллега создал запись',
    nameEn: 'Colleague created a booking',
    nameHy: 'Գործընկերը ստեղծել է գրանցում',
    descriptionRu: 'Другой администратор создал запись — уведомляем.',
    descriptionEn: 'Another admin created a booking — notified.',
    descriptionHy: 'Այլ ադմինիստրատոր ստեղծել է գրանցում․ ծանուցում ենք։',
    enabledDefault: true,
    availableChannels: ['adminApp', 'email', 'sms'],
    defaultScenario: ADMIN_DEFAULT,
    templateRu: 'Создана запись: {clientName}, {service}, {date} {time}, мастер: {staff}.',
    templateEn: 'Booking created: {clientName}, {service}, {date} {time}, specialist: {staff}.',
    templateHy: 'Ստեղծվել է գրանցում՝ {clientName}, {service}, {date} {time}, վարպետ՝ {staff}։',
  },
  {
    code: 41,
    recipient: 'admin',
    nameRu: 'Онлайн-запись перенесена',
    nameEn: 'Online booking rescheduled',
    nameHy: 'Առցանց գրանցումը տեղափոխվել է',
    descriptionRu: 'Онлайн-запись перенесена клиентом или системой.',
    descriptionEn: 'An online booking was rescheduled.',
    descriptionHy: 'Առցանց գրանցումը տեղափոխել է հաճախորդը կամ համակարգը։',
    enabledDefault: true,
    availableChannels: ['adminApp', 'email', 'sms'],
    defaultScenario: ADMIN_DEFAULT,
    templateRu: 'Онлайн-запись перенесена. Клиент: {clientName}. Новое время: {date} {time}.',
    templateEn: 'Online booking rescheduled. Client: {clientName}. New time: {date} {time}.',
    templateHy: 'Առցանց գրանցումը տեղափոխվել է։ Հաճախորդ՝ {clientName}։ Նոր ժամ՝ {date} {time}։',
  },
  {
    code: 12,
    recipient: 'admin',
    nameRu: 'Клиент отменил онлайн-запись',
    nameEn: 'Client cancelled online',
    nameHy: 'Հաճախորդը չեղարկել է առցանց գրանցումը',
    descriptionRu: 'Клиент отменил онлайн-запись сам.',
    descriptionEn: 'A client cancelled their online booking.',
    descriptionHy: 'Հաճախորդն ինքն է չեղարկել առցանց գրանցումը։',
    enabledDefault: true,
    availableChannels: ['adminApp', 'email', 'sms'],
    defaultScenario: ADMIN_DEFAULT,
    templateRu: 'Онлайн-запись отменена клиентом. Клиент: {clientName}. Время: {date} {time}.',
    templateEn: 'Online booking cancelled by the client. Client: {clientName}. Time: {date} {time}.',
    templateHy: 'Հաճախորդը չեղարկել է առցանց գրանցումը։ Հաճախորդ՝ {clientName}։ Ժամ՝ {date} {time}։',
  },
  {
    code: 19,
    recipient: 'admin',
    nameRu: 'У сотрудника заканчивается график',
    nameEn: 'Staff schedule running out',
    nameHy: 'Աշխատակցի գրաֆիկը մոտենում է ավարտին',
    descriptionRu: 'У сотрудника скоро заканчивается открытое расписание — пора открыть окна дальше.',
    descriptionEn: 'A staff member’s open schedule is about to run out — time to open more slots.',
    descriptionHy: 'Աշխատակցի բաց գրաֆիկը շուտով կավարտվի․ ժամանակն է բացել հաջորդ ժամերը։',
    enabledDefault: true,
    availableChannels: ['sms'],
    defaultScenario: { sms: 'always' },
    templateRu: 'Сотрудник: {staff}. Расписание открыто ещё на {days} дн. Откройте окна на следующую неделю.',
    templateEn: 'Staff: {staff}. The schedule is open for {days} more day(s). Open slots for next week.',
    templateHy: 'Աշխատակից՝ {staff}։ Գրաֆիկը բաց է ևս {days} օր։ Բացեք հաջորդ շաբաթվա ժամերը։',
    systemLocked: true,
  },
  {
    code: 11,
    recipient: 'staff',
    nameRu: 'Клиент записался к вам',
    nameEn: 'Client booked with you',
    nameHy: 'Հաճախորդը գրանցվել է ձեզ մոտ',
    descriptionRu: 'Клиент записался онлайн к сотруднику.',
    descriptionEn: 'A client booked online with the staff member.',
    descriptionHy: 'Հաճախորդը առցանց գրանցվել է աշխատակցի մոտ։',
    enabledDefault: true,
    availableChannels: ['adminApp', 'email', 'sms'],
    defaultScenario: ADMIN_DEFAULT,
    templateRu: 'К вам записались: {clientName}, {service}, {date} {time}.',
    templateEn: 'You have a new client: {clientName}, {service}, {date} {time}.',
    templateHy: 'Ձեզ մոտ գրանցվել են՝ {clientName}, {service}, {date} {time}։',
  },
  {
    code: 57,
    recipient: 'staff',
    nameRu: 'Вам назначили клиента',
    nameEn: 'You were assigned a client',
    nameHy: 'Ձեզ նշանակել են հաճախորդ',
    descriptionRu: 'Администратор записал клиента к сотруднику.',
    descriptionEn: 'An admin booked a client with the staff member.',
    descriptionHy: 'Ադմինիստրատորը հաճախորդին գրանցել է աշխատակցի մոտ։',
    enabledDefault: true,
    availableChannels: ['adminApp', 'email', 'sms'],
    defaultScenario: ADMIN_DEFAULT,
    templateRu: 'Вам назначена запись: {clientName}, {service}, {date} {time}.',
    templateEn: 'You have been assigned a booking: {clientName}, {service}, {date} {time}.',
    templateHy: 'Ձեզ նշանակվել է գրանցում՝ {clientName}, {service}, {date} {time}։',
  },
  {
    code: 42,
    recipient: 'staff',
    nameRu: 'Вашу запись перенесли',
    nameEn: 'Your booking was rescheduled',
    nameHy: 'Ձեր գրանցումը տեղափոխվել է',
    descriptionRu: 'Запись к сотруднику перенесена.',
    descriptionEn: 'A booking with the staff member was rescheduled.',
    descriptionHy: 'Աշխատակցի մոտ գրանցումը տեղափոխվել է։',
    enabledDefault: true,
    availableChannels: ['adminApp', 'email', 'sms'],
    defaultScenario: ADMIN_DEFAULT,
    templateRu: 'Ваша запись перенесена. Клиент: {clientName}. Новое время: {date} {time}.',
    templateEn: 'Your booking was rescheduled. Client: {clientName}. New time: {date} {time}.',
    templateHy: 'Ձեր գրանցումը տեղափոխվել է։ Հաճախորդ՝ {clientName}։ Նոր ժամ՝ {date} {time}։',
  },
  {
    code: 13,
    recipient: 'staff',
    nameRu: 'Вашу запись отменили',
    nameEn: 'Your booking was cancelled',
    nameHy: 'Ձեր գրանցումը չեղարկվել է',
    descriptionRu: 'Запись к сотруднику отменена.',
    descriptionEn: 'A booking with the staff member was cancelled.',
    descriptionHy: 'Աշխատակցի մոտ գրանցումը չեղարկվել է։',
    enabledDefault: true,
    availableChannels: ['adminApp', 'email', 'sms'],
    defaultScenario: ADMIN_DEFAULT,
    templateRu: 'Ваша запись отменена. Клиент: {clientName}. Время: {date} {time}.',
    templateEn: 'Your booking was cancelled. Client: {clientName}. Time: {date} {time}.',
    templateHy: 'Ձեր գրանցումը չեղարկվել է։ Հաճախորդ՝ {clientName}։ Ժամ՝ {date} {time}։',
  },
  {
    code: 76,
    recipient: 'staff',
    nameRu: 'Ваш клиент не пришёл',
    nameEn: 'Your client did not show up',
    nameHy: 'Ձեր հաճախորդը չի եկել',
    descriptionRu: 'Клиент не пришёл на запись к сотруднику.',
    descriptionEn: 'The client did not show up for a booking with the staff member.',
    descriptionHy: 'Հաճախորդը չի եկել աշխատակցի մոտ գրանցմանը։',
    enabledDefault: true,
    availableChannels: ['adminApp', 'email', 'sms'],
    defaultScenario: ADMIN_DEFAULT,
    templateRu: 'Клиент не пришёл: {clientName}, {date} {time}. Время свободно.',
    templateEn: 'Client no-show: {clientName}, {date} {time}. The slot is free.',
    templateHy: 'Հաճախորդը չի եկել՝ {clientName}, {date} {time}։ Ժամն ազատ է։',
  },
  {
    code: 43,
    recipient: 'adminStaff',
    nameRu: 'Подписка скоро закончится',
    nameEn: 'Subscription expiring soon',
    nameHy: 'Բաժանորդագրությունը շուտով կավարտվի',
    descriptionRu: 'Подписка на платформу скоро закончится.',
    descriptionEn: 'The platform subscription is about to expire.',
    descriptionHy: 'Հարթակի բաժանորդագրությունը շուտով կավարտվի։',
    enabledDefault: true,
    availableChannels: ['adminApp', 'email', 'sms'],
    defaultScenario: ADMIN_DEFAULT,
    templateRu: 'Подписка заканчивается {date}. Продлите, чтобы не потерять доступ.',
    templateEn: 'Subscription ends {date}. Renew to keep access.',
    templateHy: 'Բաժանորդագրությունն ավարտվում է {date}։ Երկարացրեք, որպեսզի չկորցնեք մուտքը։',
    systemLocked: true,
  },
];

/** Служебные типы без страницы настройки (F-05-004: 15, 22) — только имя, для журнала/каталога */
export const SERVICE_TYPES: { code: number; nameRu: string; nameEn: string; nameHy: string }[] = [
  { code: 15, nameRu: 'Сообщение из карточки клиента', nameEn: 'Message from client card', nameHy: 'Հաղորդագրություն հաճախորդի քարտից' },
  { code: 22, nameRu: 'Сетевая рассылка', nameEn: 'Network mailing', nameHy: 'Ցանցային առաքում' },
];

export function typeDefByCode(code: number): TypeDef | undefined {
  return TYPE_REGISTRY.find((d) => d.code === code);
}
